### ISSUE TITLE
is it a must to declare a schema upfront..? 

### ISSUE THREAD

**Issue by ianmuhia** [jtlabsio/mongo#5]

**Comment by brozeph** [comment]
Hi @Ianmuhia, in the module's current state, it is required to declare at least part of the schema up-front (the pieces of the schema, specifically, that you wish to filter, sort, or project on). However, I'm interested in understanding your usecase a little more... would you be willing to share what you are trying to accomplish?

**Comment by scheibling** [comment]
@brozeph Can't answer for lanmuhia directly, but based on my usage I'd guess that the issue arises when used with web frameworks and existing structs for modelling and validation. No matter if struct or interface[string]interface{} they don't conform to the standard required to enter them into the NewQueryBuilder-function.

I've kind of solved this for my purposes by writing a small (incomplete, won't cover all use cases) function that converts the json/bson-annotated struct to a primitive.M-compatible object:

```go
import (
	"log"
	"reflect"

	"github.com/s-augustovitko/mongo-schema-go/pkg/schema"
	"go.mongodb.org/mongo-driver/bson"
)

func BsonConvert(inp map[string]interface{}) bson.M {
	bsc := make(bson.M)
	for k, v := range inp {
		if k == "bsonType" && reflect.TypeOf(v).String() == "[]string" {
			bsc[k] = v.([]string)[0]
			continue
		}
		if v2, ok := v.(map[string]interface{}); ok {
			bsc[k] = BsonConvert(v2)
			continue
		}
		bsc[k] = v
	}
	return bsc
}

func GetBsonSchema(inp interface{}) bson.M {
	bModel, _, err := schema.Marshal(inp, "Product Schema", true)
	if err != nil {
		log.Panicf("Could not parse schema: %v", err)
	}

	bsonconvt := BsonConvert(bModel["validator"].(map[string]interface{}))
	return bsonconvt
}
```

Meaning I can generally just throw an json-annotated struct into the function and get a functional schema out of it. mongo-schema-go handles 99% of the work, BsonConvert basically just converts it to bson.M and fixes an inconsistency with the bsonType being []string instead of string


It would be convenient though to have functionality for passing a struct or a map[string]interface{} instead of just bson.M. I might have overlooked a much easier method for converting between the two, haven't worked all that much with the latter

**Comment by brozeph** [comment]
@scheibling Thank you for providing this background... I especially like your suggestion regarding the ability to pass a `map[string]any` for field / schema definition as opposed to a `bson.M`.

**Comment by scheibling** [comment]
Thanks! Otherwise this is a fantastic package, saved me a lot of time this week :)
